### ISSUE TITLE
Receiving undefined error when reuqesting matic

### ISSUE THREAD

**Issue by voidf1sh** [TamtamHero/polygon-faucet#1]
After connecting MetaMask and completing recaptcha and clicking Receive, I get an `undefined` error.

![image](https://user-images.githubusercontent.com/10382512/120879101-0fbd6e00-c58f-11eb-934c-e84585acbb7b.png)

**Comment by DemonRx** [comment]
Same issue when I try to claim MATIC. Is this faucet drained?

**Comment by voidf1sh** [comment]
It ended up working for me later in the day, I think the server is just seeing a lot more traffic than usual and may be having issues, keep trying, it eventually worked for me all 3 times From: DemonSent: Monday, June 7, 2021 3:06 AMTo: TamtamHero/polygon-faucetCc: Christian Berry; AuthorSubject: Re: [TamtamHero/polygon-faucet] Receiving undefined error when reuqesting matic (#1) Same issue when I try to claim MATIC. Is this repo / faucet. Is the faucet drained?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DemonRx** [comment]
![image](https://user-images.githubusercontent.com/18432686/121281515-02152a80-c8a6-11eb-957a-d8500c5fa159.png)

That's as far as it goes. Not even getting the undefined notification. It's just stuck at "sending"

**Comment by DemonRx** [comment]
Still having this issue. Hasn't worked once for me. I see there's other issues on this repo and no response from the developer.

Must be a dead faucet.

**Comment by TamtamHero** [comment]
The backend crashed while I was on vacation, I restarted it yesterday, sorry for the service interruption

**Comment by DemonRx** [comment]
Thank you it worked !
