### ISSUE TITLE
Support for integrating the faucet with the wallet.

### ISSUE THREAD

**Issue by Abhimanyu121** [TamtamHero/polygon-faucet#11]
Hey,
We are working on a Matic-focused wallet called Orange Wallet, can we please get some details regarding how we can integrate this faucet with our wallet.

**Comment by Richienb** [comment]
1. Get the user's wallet address
2. Show a hCaptcha with the site-key `d712e7c4-b981-4761-bb8c-c7af95d016dd`
3. Send a HTTP GET to `https://backend.matic.supply:3000/rpc-mainnet/matic/<wallet>/<captcha_token>`
4. If response code is 200, get `hash` from the json response and give the user a url to the transaction: `https://polygonscan.com/tx/<hash>`

Relevant implementation:

https://github.com/TamtamHero/polygon-faucet/blob/7434870d6d10a368d95e4bf4e300d7ede60dd0ad/frontend/src/controller/faucet.js#L6-L14

**Comment by Abhimanyu121** [comment]
Hey, thanks a lot, we wiil do it.

**Comment by Abhimanyu121** [comment]
Hey we have integrated it with our wallet but the server is sending undefined way too frequently, can this be resolved or can we help in resolving this in some way?
Btw, here is a link to the wallet.
https://play.google.com/store/apps/details?id=org.orange.wallet

**Comment by Richienb** [comment]
Note how the main website is also experiencing this issue

https://github.com/TamtamHero/polygon-faucet/issues/13

**Comment by TamtamHero** [comment]
Sorry, I was out for summer, should be fixed
