### ISSUE TITLE
Uncaught error in faucet

### ISSUE THREAD

**Issue by vishusingh** [TamtamHero/polygon-faucet#16]
On clicking receive, the app throws an error in the console and the sending request fails.

![CleanShot 2021-08-11 at 07 32 08](https://user-images.githubusercontent.com/11193457/128974891-bc6e750d-5950-48ed-ac8f-f7fe81c033e1.png)

**Comment by Vivero** [comment]
Getting the same error as well

**Comment by DenhamPreen** [comment]
It seems the error is not returning a data prop
![image](https://user-images.githubusercontent.com/26438203/130047820-d95581b9-2680-45ed-9589-ea87e7058df8.png)
It seems users are still claiming from contract so my naive guess is the error is probably coming from an rpc error 
https://polygonscan.com/address/0x8C5a6C767Ee7084a8C656Acd457Da9561163aE7E

**Comment by TamtamHero** [comment]
Sorry, I was out for summer, fixed
