### ISSUE TITLE
api timeout is not handled properly

### ISSUE THREAD

**Issue by tv104** [TamtamHero/polygon-faucet#2]
This seem to be due to the `error` object not containing `error.response`. When this happens, the UI button is frozen and no UI notification of something going wrong is displayed.

![image](https://user-images.githubusercontent.com/1164786/120892007-340b6000-c60c-11eb-98d6-1e244cc9887c.png)

**Comment by MylesMor** [comment]
This happens to me as well, the lack of timeout error handling means there is no indication of failure provided to the client-side.

**Comment by TaldenV** [comment]
On the miannet it shows that there have been no transactions out of the dapp. It shows there's crypto in there, but nothing is moving. 

<img width="1299" alt="Screen Shot 2021-06-05 at 4 26 19 PM" src="https://user-images.githubusercontent.com/26146844/120906946-c61a6500-c61a-11eb-8de2-94dd8135bb4d.png">

**Comment by githistory** [comment]
Network Error connecting to `backend.matic.supply:3000`. Backend server might be down. Need @TamtamHero to restart it I guess.

**Comment by TamtamHero** [comment]
The backend crashed while I was on vacation, I restarted it yesterday, sorry for the service interruption
