### ISSUE TITLE
No response from faucet. Checked the console, have some error

### ISSUE THREAD

**Issue by rndmzr** [TamtamHero/polygon-faucet#3]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://backend.matic.supply:3000/rpc-mainnet/matic`

`Uncaught (in promise) TypeError: e.response is undefined
    onClick App.js:63
`

**Comment by vmaark** [comment]
similar error:
App.js:63 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at App.js:63

**Comment by Shorshaa** [comment]
The previous error happens when the connection is refused. 
the connection is going to https://backend.matic.supply:3000/rpc-mainnet/matic but that port is not open (blocked somehow) or the server hung and need to be restarted
![2021-06-07 23_37_52-Matic Supply](https://user-images.githubusercontent.com/85535406/121114225-bb61fa80-c7e9-11eb-9dc7-cf50b7104c2d.png)

**Comment by psbrandt** [comment]
It's a CORS error because of this:

https://github.com/TamtamHero/polygon-faucet/blob/3516d2bc504d3268e36bace8aaa7e53a64a77db9/server/index.js#L9

This PR might fix it: https://github.com/TamtamHero/polygon-faucet/pull/4, but it could also just be that the server is down.

**Comment by kamicup** [comment]
I see same error as shorshaa wrote.
Disabling cors feature of chrome does not effect.
curl also failed to connect to the server, so it seems to be not available.

**Comment by Shorshaa** [comment]
I see no updates but it ran fine today (just used it a few minutes ago). Do anyway know what was the real issue finally?

**Comment by TamtamHero** [comment]
The backend crashed while I was on vacation, I restarted it yesterday, sorry for the service interruption

**Comment by vasylsheremet1** [comment]
Again the same error

**Comment by TamtamHero** [comment]
Sorry, I was out for the summer, it should be fixed now

**Comment by Tekvektor** [comment]
Still occurring in Chrome.

**Comment by Marcusg62** [comment]
I am having this issue right now. Both in Brave and Chrome. 
![image](https://user-images.githubusercontent.com/21998115/132601882-fae0eb79-3951-4161-bd0a-6d37ca20b4b1.png)
