### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by gsscoder** [TamtamHero/polygon-faucet#32]
I got always Network error

I tried to inspect the HTTP call but there's no response

![image](https://user-images.githubusercontent.com/1194228/157686342-876798dc-c830-4157-bebd-33b9a1977176.png)

Bye :)

**Comment by guser56789** [comment]
I've also been having "Network Error" problems for 2 days.

**Comment by kelvindevv** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by gsscoder** [comment]
Difficult to spot with developer tools

**Comment by eugene-can** [comment]
The https certificate expired, need to be renewed.

**Comment by LordDraagonLive** [comment]
Still, the certificate is not renewed. Can we run this locally and try?

**Comment by TamtamHero** [comment]
renewed certificate, sorry for delay
