### ISSUE TITLE
The faucet isn't working

### ISSUE THREAD

**Issue by ninjamar** [TamtamHero/polygon-faucet#33]
The faucet isn't working It hasn't sent out MATIC in a while (https://polygonscan.com/address/0x8C5a6C767Ee7084a8C656Acd457Da9561163aE7E/transactions) <br>
It also keeps saying Network Error. I think the backend is sending out a 500 error.

**Comment by TamtamHero** [comment]
Indeed, the balance has emptied. The decrease in balance doesn't seem very organic (https://polygonscan.com/address/0x8C5a6C767Ee7084a8C656Acd457Da9561163aE7E/transactions#analytics)
Somehow, someone is slowly draining the faucet despite the captcha :(

**Comment by TamtamHero** [comment]
replenished, thanks for pinging me
