### ISSUE TITLE
Is this faucet dead?  Error on website for about a week now.

### ISSUE THREAD

**Issue by dfarr-bitulent** [TamtamHero/polygon-faucet#5]
Please let us know if this faucet is no longer functioning.  Has not been working due to CORS and other errors for about a week now.

**Comment by mattharvill** [comment]
+1

**Comment by thetylerhayes** [comment]
+2

**Comment by KYCgrayson** [comment]
+3 i love the project initiative and had donate MATIC as well. will be great if it is back on line.

**Comment by TamtamHero** [comment]
The backend crashed while I was on vacation, I restarted it yesterday, sorry for the service interruption
