### ISSUE TITLE
Faucet server issue, might be CORS

### ISSUE THREAD

**Issue by BrianM0330** [TamtamHero/polygon-faucet#7]
As others have mentioned, there's an issue where the faucet gets stuck at 'sending' because of CORS. I tried disabling cors on Firefox 89 as well as Chrome, but it didn't seem to do anything. #4 seems to attempt to fix this, but as some of the commenters mentioned it could just be something with the server. 

I attached the log from where it gets stuck.
[maticfaucet.txt](https://github.com/TamtamHero/polygon-faucet/files/6635129/maticfaucet.txt)

**Comment by TamtamHero** [comment]
The backend crashed while I was on vacation, I restarted it yesterday, sorry for the service interruption
