### ISSUE TITLE
ERR_CONNECTION_REFUSED Error

### ISSUE THREAD

**Issue by huangtony** [TamtamHero/polygon-faucet#8]
Hi,
I'm getting this error, perhaps the server crashed again?

GET https://backend.matic.supply:3000/rpc-mainnet/matic/0xfc30173690bb46feb166a8ce01e13659d9e4156d/P0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiVTY2UVplZitFSHo4blNvWjFyMWtDWGRLaWtUZFhub2JqYXFMUXZlRTY2K1I1VFNVcWw3NW5BNzdKbThHTm5tQW1tK1N5b0dGUGZJeGZibFF6ZmhHdE9QRmdRcUh3UnlCUFpSV1FjeHJ2N0tMMFh2Qk5sblJWMTVnOU1kSVlsN2RjUmJQaXUrM3ZUd1l3TjB4R0JCVHZxWlVUczlQSzlqTEhwUWN3OGxKVG42RzBDbGV0ci9sNUlCYktkRUpHeTV3OUQzajJyeklOVU9pamY3aGV2ZVVZYWlnMTdBLzJZK3JydXl3SFliMjQwK2sxeFRFOEowZytESk91d1dMZWVPMFVrMzdKNC9ab2xBYkNuN1JWNEdJNnhxV2NnR29UQ3JUTjlia2FodGFseThxcDhsdzRRSDdoVFkvYXcxZjZYS0I2STZjaUZtNVBkV1Fuc2RjdFh2dC9xTWZ6ZFdjT3gwb1V1dkV0eE52M2lnNWVVOUF4Wm8zUm9tSTM1aUYvWDNTYjBqajhadndaa0pET3ZwTk9ZeXdoME9yNG5QNnhZZzZDb0pkbU5ZSEorZnZHWHMxUnNqSUFzQzd4RldYMnhhcnJBeGlGK0FLNTFIMTMrb0l6ZjB3TS82OXdKS2J4RnpESHdMUWluZS9tYytnR0xoSFNROC9sUHRVOGovQWQ5SHlxMzZ1Y1lvRk5XOEZwbmp6Qkdwci8xaDVGK0h2VXo3OTJ3bkZXNHg4ZkV6WEE0d2xLc3E1UTllZ1FZUC9pK3lnbzduamkrQnlCSUdvajY2ZnlhTHBXWWpVY3lqYlhoWklxR0F3VjVtU0NuY05TUWttV2VXeHRHODcrOGxPenErdmxSTE45OHVXd0VJMjNiSm9obGpnRno4MWhHTjQ1UE0rTkttZFZXd3Qva09qYUhRckZEUWtoZnp2cVFwbDl4TFlKNmYraHduL3NZUWxRTTh4dFlXYmZkTkIwaHg3MVNjbDlmUnNKNWsyTVhYTjFnNkJ0bE5VT2MzV1ZKVTdEQnVFU0NpdUMyVnBwY2pCZ2gvZ3RWVTFXVG9NMDMxSE8wUk8wdU5VYy8zSlR0c1cvcE9DeElxOXFpQ0tEdG1RTlk5cjRiaFBSenZNWVViV2hFOS81M0FObEc5emVBZDN6bHQrMldKazI5M1BlV2dhYWlkYm90aUhkb2F0TkFRMEU4WVoxSnB4Zy9JMTh4OGxGTnBrMWRxT25ybUljbUFUSjRvdGtmVjdzMWZQL3FTSUIrOGoyN2wxTU1VRE44eW5CSmNvUUZydC9uVXYyaXJMTkFWWDVnV0pTYW1Ecmo4L0VYbUxBYnd0RUlVY01aRzVrVEhKYUEzR1JDMU14TlNyWXhoNjdJUU5sSVFHdk53Z1pmRUZWN1ZCeEt3YXJHMFN2NTBqSXMyOHdoamdUUjM5eVg2T0s2ejFwV0ZHZG5JWXY1S2hIVVJBUldQM2VrRE8iLCJleHAiOjE2MjQ1MjI5OTUsInNoYXJkX2lkIjozNjI0MDY5OTYsInBkIjowfQ.K1n2DwZXtJHHw6csXfRrbMrRUL-VavxJNWfdnUIB8ng net::ERR_CONNECTION_REFUSED

**Comment by TamtamHero** [comment]
Sorry, I was out for the summer, it should be fixed now
