### ISSUE TITLE
Not enough MATIC rewarded to deposit funds on aave

### ISSUE THREAD

**Issue by DemonRx** [TamtamHero/polygon-faucet#9]
![Screenshot from 2021-06-26 18-08-45](https://user-images.githubusercontent.com/18432686/123527004-cb168580-d6a9-11eb-8d7a-c48042875e37.png)

This is technically inaccurate. As I've received 0.001 MATIC from this faucet, However, I'm unable to deposit MATIC into aave:
![Screenshot from 2021-06-26 18-03-42](https://user-images.githubusercontent.com/18432686/123527018-ebdedb00-d6a9-11eb-9663-dd52b6d662ba.png)

![Screenshot from 2021-06-26 18-07-54](https://user-images.githubusercontent.com/18432686/123527029-0749e600-d6aa-11eb-88e7-e294b8c0214a.png)

I'm not sure what's going on here, unless the platform requires a larger MATIC balance to deposit ?

**Comment by lookfirst** [comment]
It says "deposit some fund"... they are assuming you'll use the matic for the transaction of OTHER funds.

**Comment by DemonRx** [comment]
Ah! forgot this was still open. I ended up getting more MATIC and was able to deposit. However, aave's faq page states:

>You can deposit any amount you want, there is no minimum or maximum limit. Still, it's important to take into account that for really low amounts it is  possible that the transaction cost of the process is higher than the expected earnings. It is recommended that you consider this when depositing very low amounts. 

https://docs.aave.com/faq/depositing-and-earning#:~:text=You%20can%20deposit%20any%20amount,no%20minimum%20or%20maximum%20limit.

It seems they fixed this, as I was able to deposit micro amounts. You just need to make sure you have enough MATIC in your wallet to cover transaction fees.

For anyone coming across this, there's a platform that pays out MATIC just for holding their token in your wallet. 

https://app.spacerat.finance/

Works like a faucet. You can claim your portion every 3 days.
